//
//  BadHabitsPresenter.swift
//  MeditationApp
//
//  Created by Anatoly Kustov on 25.11.2019.
//  Copyright (c) 2019 Anatoly Kustov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BadHabitsPresentationLogic
{
  func presentSomething(response: BadHabits.Something.Response)
}

class BadHabitsPresenter: BadHabitsPresentationLogic
{
  weak var viewController: BadHabitsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: BadHabits.Something.Response)
  {
    let viewModel = BadHabits.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
