//
//  MeditationInteractor.swift
//  MeditationApp
//
//  Created by Anatoly Kustov on 25.11.2019.
//  Copyright (c) 2019 Anatoly Kustov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MeditationBusinessLogic
{
  func doSomething(request: Meditation.Something.Request)
}

protocol MeditationDataStore
{
  //var name: String { get set }
}

class MeditationInteractor: MeditationBusinessLogic, MeditationDataStore
{
  var presenter: MeditationPresentationLogic?
  var worker: MeditationWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Meditation.Something.Request)
  {
    worker = MeditationWorker()
    worker?.doSomeWork()
    
    let response = Meditation.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
